services:
  - type: web
    name: pdf_qa
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 1000085
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
